# Generated by Django 5.2.8 on 2026-01-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='pushupvideosmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExerciseAnalysis',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
